//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vk347vivekkhatriEntities : DbContext
    {
        public Vk347vivekkhatriEntities()
            : base("name=Vk347vivekkhatriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<City342> City342 { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Country342> Country342 { get; set; }
        public virtual DbSet<diagnosi> diagnosis { get; set; }
        public virtual DbSet<medicine> medicines { get; set; }
        public virtual DbSet<State342> State342 { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<StudentData> StudentDatas { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<treatmentdetail> treatmentdetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User343> User343 { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<otp> otps { get; set; }
    }
}
