//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string Lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> usertypeid { get; set; }
        public string Address { get; set; }
        public string mobileno { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
    
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual state state { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
